# (HTTP and SOCKS5 in one port)
mixed-port: 7890
mode: rule
log-level: warning
proxies:
  - name: "v2y"
    type: vmess
    server: server3_of_ss
    port: 443
    uuid: uuid
    alterId: 0
    cipher: auto
proxy-groups:
  - name: "auto"
    type: url-test
    proxies:
      - v2y
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
rules:
  - DOMAIN-SUFFIX,google.com,DIRECT
  - DOMAIN-KEYWORD,google,DIRECT
  - DOMAIN,google.com,DIRECT
  - DOMAIN-SUFFIX,github.com,DIRECT
  - DOMAIN-KEYWORD,github,DIRECT
  - DOMAIN,github.com,DIRECT
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,CN,DIRECT
  # - IP-CIDR,127.0.0.0/8,DIRECT
  # - DST-PORT,80,DIRECT
  # - SRC-PORT,7777,DIRECT
  - MATCH,DIRECT
