format = """
$username\
$hostname\
$localip\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$golang\
$helm\
$lua\
$nodejs\
$python\
$rust\
$conda\
$memory_usage\
$direnv\
$env_var\
$sudo\
$cmd_duration\
$line_break\
$time\
$container\
$shell\
$character"""

# 设置配置范例，开启编辑器的自动补全
"$schema" = 'https://starship.rs/config-schema.json'

# 在命令之间插入空行
add_newline = false

[character]
success_symbol = "[>>](bold green)"
error_symbol = "[xx](bold red)"
vicmd_symbol = "[vi](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
conflicted = "c"
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "-"
modified = "!"
untracked = "u"
stashed = "s"
staged = "+"
ignore_submodules = true

[username]
format = "[$user]($style) "

[hostname]
ssh_only = true
ssh_symbol = "ssh="

[bun]
symbol = "bun "

[c]
symbol = "C "

[conda]
symbol = "conda "

[cmake]
symbol = "cmake "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[python]
symbol = "py "

[rust]
symbol = "rs "

[sudo]
symbol = "sudo "
disabled = true

[rlang]
symbol = "R "

[kubernetes]
disabled = false
symbol = "k8s="

[time]
disabled = true
time_format = "%Y-%m-%d %H:%M:%S"

[helm]
symbol = "helm "
